[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*"]

[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
